### ISSUE TITLE
Impact graph colors make text hard to read (at least for a red/green colorblind person!)

### ISSUE THREAD

**Issue by wlupton** [YangCatalog/search#11]
In general I have trouble distinguishing "similar" shades of red, green and brown. But my specific comment here is on the contrast between the green (?) used for BBF and the white text. If I zoom right in I can see it (first example), but if there are several nodes on the screen (second example) I won't be able to read it.

![screen shot 2018-10-29 at 10 40 34](https://user-images.githubusercontent.com/8874729/47644821-209bdc80-db67-11e8-9114-078454bf5659.png)

![screen shot 2018-10-29 at 10 42 37](https://user-images.githubusercontent.com/8874729/47644919-66f13b80-db67-11e8-80de-9fd84af3b330.png)

**Comment by evyncke** [comment]
Indeed, even for the non colorblind people, it is a poor choice.

Let's try to fix this issue at the IETF Hackathon this WE

-éric

**Comment by wlupton** [comment]
I will be there and happy to help :).

**Comment by miroslavKovacPantheon** [comment]
@wlupton  could you confirm that it is more readable right now? I picked sever colors statically that will always be used for organizations, let me know if the choice of colors are still wrong.. thank you

**Comment by miroslavKovacPantheon** [comment]
I am closing this issue since there was no answer and the fix was provided and no other problem like this was submitted..
