### ISSUE TITLE
Impact graph submodule display

### ISSUE THREAD

**Issue by wlupton** [YangCatalog/search#13]
I'm probably misunderstanding the controls, but why don't I see submodules here? the bbf-fast module has MANY submodules!

![screen shot 2018-10-29 at 10 52 44](https://user-images.githubusercontent.com/8874729/47645564-4c1fc680-db69-11e8-8911-67dc02db0792.png)

**Comment by wlupton** [comment]
Note that I set recursion levels to 10 because I thought it might help. But it didn't seem to make any difference (obviously I don't know what it does!).

**Comment by miroslavKovacPantheon** [comment]
Submodules are properly showed again
