### ISSUE TITLE
Impact graph "ERROR! Loop found {} <=> {}" errors

### ISSUE THREAD

**Issue by wlupton** [YangCatalog/search#14]
Following on from #13, I tried explicitly mentioning a submodule and get what you see below.

![screen shot 2018-10-29 at 11 00 07](https://user-images.githubusercontent.com/8874729/47645792-e8e26400-db69-11e8-8761-77ba89dec79f.png)
![screen shot 2018-10-29 at 11 00 19](https://user-images.githubusercontent.com/8874729/47645800-ed0e8180-db69-11e8-9cf7-44ff48dbff7b.png)
![screen shot 2018-10-29 at 11 00 27](https://user-images.githubusercontent.com/8874729/47645810-f0097200-db69-11e8-9a21-1690efdfc435.png)

**Comment by miroslavKovacPantheon** [comment]
fixed with #15
