### ISSUE TITLE
Impact graph submodule support

### ISSUE THREAD

**Issue by wlupton** [YangCatalog/search#15]
Naively I would expect a module (if not showing submodules) to look the same in the impact graph as if there were no submodules. So for example I’d expect bbf-fast to show a connection to ietf-interfaces. (Presence or absence of submodules is an implementation detail and often not relevant for impact analysis.)

Perhaps the "_Include Sub-modules?_" checkbox could enable/disable a mode that either completely exposes or completely hides submodules? If hidden, I wouldn't expect them to be available for either name completion or display.

**Comment by miroslavKovacPantheon** [comment]
It should work exactly as you described. submodules are fixed. Please use yang.amsl.com instead of yangcatalog.org. we are in a process of transfering servers and yangcatalog.org is outdated at the moment.
