### ISSUE TITLE
yang-search does not find iana-bfd-types

### ISSUE THREAD

**Issue by Reshad-Rahman** [YangCatalog/search#18]
I used https://yangcatalog.org/yang-search/ to search for
1) iana-bfd-types@2018-08-01.yang
2) iana-bfd-types.yang
3) iana-bfd-types

All 3 searched failed and IMO all 3 should work. That module is from https://datatracker.ietf.org/doc/draft-ietf-bfd-yang/

**Comment by miroslavKovacPantheon** [comment]
Hi,

Thank you for opening the issue.

Not sure what are you trying to accomplish or find.. Also I am not sure why the third one didn t work for you it did for me. It could have been updated in a meantime.. but if you are trying to find metadata details of the module you should search in here... https://yangcatalog.org/yang-search/module_details/?module=iana-bfd-types

**Comment by Reshad-Rahman** [comment]
Hi,

3 does work for me now. I thought it'd be handy to have 1 also (i.e. a module with a specific date) but it's not a must.

Thanks,
Reshad.
