### ISSUE TITLE
Module metadata missing some information

### ISSUE THREAD

**Issue by Reshad-Rahman** [YangCatalog/search#21]
Comparing https://yangcatalog.org/yang-search/module_details/?module=iana-bfd-types
to https://old.yangcatalog.org/yang-search/module_details.php?module=iana-bfd-types

The compilation status field was initially empty, on refresh it came up.
But after refresh the dependencies info was missing, whereas it is present in the old catalog. This could be related to https://github.com/YangCatalog/backend/issues/42

**Comment by miroslavKovacPantheon** [comment]
Hi,

this issue together with YangCatalog/backend#42 should be fixed now.. thanks for reporting

**Comment by miroslavKovacPantheon** [comment]
Closing this issue. The url changed a little for this issue https://yang.amsl.com/yang-search/module_details/?module=iana-bfd-types
