### ISSUE TITLE
Multiple identical entries in YANG Search

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/search#25]
Hi,

https://www.yangcatalog.org/yang-search/ => search for ietf-interfaces, with default search options
The first two entries (admin-status) are similar.

Name | Revision | Schema Type | Path | Module | Origin | Organization | Maturity | Imported By # Modules | Compilation Status | Description
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
admin-status | 2018-02-20 | leaf | /if:interfaces-state/if:interface/if:admin-status | ietf-interfaces                              ( Module Details \|                                                      Tree View                           \|                                                        Impact Analysis) | Industry Standard | ietf | ratified | 200 | passed | The desired state of the interface.  This leaf has the same read semantics as ifAdminStatus.
admin-status | 2018-02-20 | leaf | /if:interfaces/if:interface/if:admin-status | ietf-interfaces                              ( Module Details \|                                                      Tree View                           \|                                                        Impact Analysis) | Industry Standard | ietf | ratified | 200 | passed | The desired state of the interface.  This leaf has the same read semantics as ifAdminStatus.

Maybe identical/related to https://github.com/YangCatalog/search/issues/23

**Comment by bclaise** [comment]
Well, actually the paths are different: 

  | /if:interfaces-state/if:interface/if:admin-status
  | /if:interfaces/if:interface/if:admin-status

Not sure what to do in this case. All OpenConfig YANG modules will be duplicated (under /config and /state

**Comment by miroslavKovacPantheon** [comment]
There is a option of removing node name and path from output collumns and that way it would not show duplicated
