### ISSUE TITLE
YANG search returns "ERROR! Could not find data"

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/search#26]
Hi,

See https://www.yangcatalog.org/yang-search/yang_tree/Cisco-IOS-XR-manageability-perfmgmt-oper#
Select average-cpu-used
It produces:
ERROR! Could not find data for Cisco-IOS-XR-manageability-perfmgmt-oper at /manageability-perfmgmt-oper:perf-mgmt/manageability-perfmgmt-oper:periodic/manageability-perfmgmt-oper:nodes/manageability-perfmgmt-oper:node/manageability-perfmgmt-oper:sample-xr/manageability-perfmgmt-oper:sample/manageability-perfmgmt-oper:average-cpu-used 

at https://www.yangcatalog.org/yang-search/yang_tree/show_node/Cisco-IOS-XR-manageability-perfmgmt-oper//manageability-perfmgmt-oper:perf-mgmt/manageability-perfmgmt-oper:periodic/manageability-perfmgmt-oper:nodes/manageability-perfmgmt-oper:node/manageability-perfmgmt-oper:sample-xr/manageability-perfmgmt-oper:sample/manageability-perfmgmt-oper:average-cpu-used

Regards, Benoit

**Comment by miroslavKovacPantheon** [comment]
Ok I fixed this. It was a length of the query string. anything above 256 chars was ignored and path in here is 260 chars.. also all the others that were longer than that didn t work but now they are working.

Please check and close issue if sattisfied
Thank you
