### ISSUE TITLE
openconfig-platform display issue

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/search#27]
https://www.yangcatalog.org/yang-search/yang_tree/show_node/openconfig-platform//oc-platform:components/oc-platform:component/oc-platform:state/oc-platform:serial-no => ERROR! Could not find data for openconfig-platform at /oc-platform:components/oc-platform:component/oc-platform:state/oc-platform:serial-no

**Comment by miroslavKovacPantheon** [comment]
The url changed a little this one works.
https://www.yangcatalog.org/yang-search/yang_tree/show_node/openconfig-platform//oc-platform:components?container/oc-platform:component?list/oc-platform:state?container/oc-platform:serial-no?leaf

There was a bug when getting this from tree view.  https://www.yangcatalog.org/yang-search/module_details/?module=openconfig-platform@2018-11-21 => Tree View => Expand All => serial-no
but that url is generated fine now.

Thank you
Miroslav Kovac
