### ISSUE TITLE
ERRORS in YANG search

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/search#28]
https://www.yangcatalog.org/yang-search/impact_analysis/?modtags=ietf-routing&orgtags=&recursion=1&show_rfcs=1&show_subm=1&show_dir=both
see the two ERRORS at the top.

The issue is problem with ietf-fb-rib-types yang file.. they import ietf-access-control-lists {prefix "acls";} but there is no such module. only ietf-access-control-list with no 's' at the end of the name... that s why elasticsearch couldn t find that module. this is module bug.

Btw, https://www.yangcatalog.org/yang-search/module_details/?module=ietf-fb-rib-types 
=> There is no supporting document. Note that the draft expired.

The ERRORS point to an issue with our tool. We should try to mention the root cause: YANG issue in ietf-fb-rib-types

**Comment by SlavomirMazurPantheon** [comment]
It is no longer displayed as an error. 
However, user is informed if some of the modules do not exist in API => they are not populated in API.
![image](https://user-images.githubusercontent.com/67378888/189966896-66da9c4c-0b7a-4279-870d-e1db6e4475f6.png)
