### ISSUE TITLE
temporary files should be UTF-8 and in the tempfile directory

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/search#30]
In build_yindex(), several temp.txt files are created and should:

1. be opened with encoding='utf-8'
2. be created in the YANG catalog temporary directory

**Comment by miroslavKovacPantheon** [comment]
fixed within this commit https://github.com/YangCatalog/search/commit/40af01ff6c745f5c4acbf1003c94344e28c87a10

Thank you
