### ISSUE TITLE
Search bug for typedef

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/search#37]
I selected only typedef and found an extension:
https://www.yangcatalog.org/yang-search/?csrfmiddlewaretoken=1bGw5QnfG0ymnnRpl9XTkws9GhV302V21fU0i0rlUxqrNABl7SnoyZBt0kOx9BI2&search_string=.*&onlyLatest=1&fieldsAll=1&searchFields%5B%5D=module&searchFields%5B%5D=argument&searchFields%5B%5D=description&yangVersions%5B%5D=1.0&yangVersions%5B%5D=1.1&schemaTypes%5B%5D=typedef&headersAll=1&headersTypes%5B%5D=Name&headersTypes%5B%5D=Revision&headersTypes%5B%5D=Schema+Type&headersTypes%5B%5D=Path&headersTypes%5B%5D=Module&headersTypes%5B%5D=Origin&headersTypes%5B%5D=Organization&headersTypes%5B%5D=Maturity&headersTypes%5B%5D=Imported+By+%23+Modules&headersTypes%5B%5D=Compilation+Status&headersTypes%5B%5D=Description&submit=Search%21

![image](https://user-images.githubusercontent.com/6932412/54929244-8bcebc80-4f15-11e9-8370-17611834c082.png)

**Comment by miroslavKovacPantheon** [comment]
this issue was because of the wrong parsing of the search details. resolved in commit above
