### ISSUE TITLE
'/var/yang/yang2_repo_cache.dat.failed' path should be taken out of yangcatalog.conf file

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/search#57]
as in title

**Comment by miroslavKovacPantheon** [comment]
fixed here 6e6ead1049c0b3f823fee23757b058ebf83562bd

**Comment by evyncke** [comment]
Hello Miroslav,

It looks like you are quite efficient today :-)

-éric

**Comment by miroslavKovacPantheon** [comment]
Yeah I am trying to clean up some issues that has been done in containerized version longer time ago but were not changed in the not containerized version before and also fixing some small easy to fix issues and this one was one of them

________________________________
Od: Eric Vyncke <notifications@github.com>
Odoslané: streda, 24. júna 2020 10:22:46
Komu: YangCatalog/search
Kópia: Miroslav Kováč; State change
Predmet: Re: [YangCatalog/search] '/var/yang/yang2_repo_cache.dat.failed' path should be taken out of yangcatalog.conf file (#57)


Hello Miroslav,

It looks like you are quite efficient today :-)

-éric
