### ISSUE TITLE
Hovering over a leaf node displays \n

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/search#96]
When hovering with the mouse over a leaf node, the pop-up DIV contains \n , which should be translated into <br/> in order to display a line break.

**Comment by SlavomirMazurPantheon** [comment]
Hello,

bug fixed on the backend side by this commit: https://github.com/YangCatalog/backend/commit/d3ea043f05a4de6ba5ed418f6849cb75ef0a23f1
Same problem also fixed in Module details - tooltip which contains description of individual properties.

Regards,
Slavomir Mazur
